name: Always build, also publish to PyPi if on master branch

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run build script
        run: >-
          bash build.sh
  publish:
    name: Publish 🐍📦 to PyPi
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
